image: Visual Studio 2017

version: '{build}'

platform:
- x64

clone_depth: 5
cache:
- '%LOCALAPPDATA%\Yarn'
- '%USERPROFILE%\.electron'
- node_modules

init:
- git config --global core.autocrlf input
- git config --system core.longpaths true

install:
- ps: Install-Product node 12 x64
- npm install yarn@1.22.10 -g
- yarn cache clean
- yarn install --force
- ps: . .\tools\install-arduinocli.ps1

build_script:
- yarn run build
- ps: . .\tools\appveyor.ps1

test: off
